apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  ports:
  - protocol: TCP
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
    name: mariadb
  type: ClusterIP
status:
  loadBalancer: {}