apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  selector:
    app: mariadb
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MARIADB_USER
              value: admin
            - name: MARIADB_DATABASE
              value: keycloak
            - name: MARIADB_PASSWORD
              value: Demoniosnohoy2020?
            - name: MARIADB_ROOT_PASSWORD
              value: Demoniosnohoy2020?
          volumeMounts:
            - name: mariadb-vol
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-vol
          persistentVolumeClaim:
            claimName: mariadb-pv-claim        
          